### ISSUE TITLE
Switch Language and Chapter Navigation

### ISSUE THREAD

**Issue by JoeNorth** [aws-samples/eks-workshop-developers#65]
**Is your feature request related to a problem? Please describe.**
Now that the Java workshop has been merged in it will make more sense to users to move the top navbar to reflect each language the workshop is available in. Currently the top navigation is showing each chapter and the sidebar is showing the language-specific content for that chapter. This makes navigation confusing though as users would expect clicking the next and previous buttons along the bottom to keep them within their language content.

**Describe the solution you'd like**
Switch the top and sidebar navigations

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by ybezsonov** [comment]
I blocked time in the end of the week for that task.

**Comment by ybezsonov** [comment]
Hi @JoeNorth Could you please re-assign it to Ramakrishnan Palaninathan @ramkifx6 ?

**Comment by JoeNorth** [comment]
> Hi @JoeNorth Could you please re-assign it to Ramakrishnan Palaninathan @ramkifx6 ?

Done

**Comment by ramkifx6** [comment]
Created the pull request - https://github.com/aws-samples/eks-workshop-developers/pull/66

**Comment by JoeNorth** [comment]
#66 Merged. Closing issue.
